# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191022_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically \t\t\t\t\t\t\t\t\t   from the title of the post', unique=True),
        ),
    ]
