# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191022_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'PostModel'},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('name', 'email')]),
        ),
    ]
